site_name: Casys.ai
site_title: Casys.ai
site_description: Documentation for the Casys RPG Interactive Game Book Engine
repo_url: https://github.com/Casys-AI/casys-rpg
repo_name: Casys-AI/casys-rpg
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/icons/android-chrome-192x192.png
  favicon: assets/icons/favicon.ico
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      archive: true
      categories: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Casys-AI/casys-rpg
    - icon: fontawesome/brands/python
      link: https://python.org
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - Overview: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Architecture:
    - Overview: architecture/overview.md
    - Cognitive Loop: architecture/cognitive-loop.md
    - Components: architecture/components.md
    - Frontend: architecture/frontend.md
  - Blog: 
    - Overview: blog/index.md
    - Posts: blog/posts/
