name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: ['main']  # ou 'master' selon ta branche principale
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: https://www.casys.ai
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps -r freeze-requirements.txt
          pip install --no-deps numpy==2.2.1
          pip install --no-deps faiss-cpu==1.9.0.post1
          pip install --no-deps langchain==0.3.13
          pip install --no-deps libsass==0.23.0
          
      - name: Verify critical dependencies
        run: |
          python -c "import numpy; print(f'Numpy version: {numpy.__version__}')"
          python -c "import langchain; print(f'Langchain version: {langchain.__version__}')"
          python -c "import sass; print(f'Libsass version: {sass.__version__}')"

      - name: Build SASS
        run: |
          python -c "import sass; sass.compile(dirname=('docs/assets/stylesheets', 'docs/assets/stylesheets'))"
          
      - name: Build site
        run: mkdocs build
        
      - name: Copy CNAME
        run: cp docs/static/CNAME site/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4